### ISSUE TITLE
NumberFormatExcepton on load 1.14

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#14]
Spigot 1.14 (2268)
TangledMaze 1.2.2
```
[09:22:12] [Server thread/INFO]: [TangledMaze] Enabling TangledMaze v1.2.2
[09:22:12] [Server thread/ERROR]: Error occurred while enabling TangledMaze v1.2.2 (Is it up to date?)
java.lang.NumberFormatException: For input string: "14-R0"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:983) ~[?:?]
        at me.gorgeousone.tangledmaze.data.Constants.loadConstants(Constants.java:56) ~[?:?]
        at me.gorgeousone.tangledmaze.core.TangledMain.onEnable(TangledMain.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:441) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:762) [spigot-1.14.jar-2019-05-05-0756:git-Spigot-1eece4f-84400e6]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by GorgeousOne** [comment]
Ah nice they changed the way how the bukkit version is written as text. But I'm not sure, does the plugin itself still work? Probably not.

**Comment by SlimeDog** [comment]
It does not. :(
