### ISSUE TITLE
Clicking with wand causes errors in console.

### ISSUE THREAD

**Issue by nunavailabul** [GorgeousOne/TangledMazes#18]
**Describe the bug**
/tangledmaze wand
Left click (console generates error)
Right Click (console generates error)

Initially I was also getting error about claims, because grief prevention uses the golden shovel.  I changed the wand item to a golden_axe to make sure it wasn't just that and still receive the error.

**Expected behavior**
Area Selection for preparation of maze build.

**Console Output**
Could not pass event PlayerInteractEvent to TangledMaze v1.2.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1222) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.gorgeousone.tangledmaze.listener.ToolActionListener.onBlockClick(ToolActionListener.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor229.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]

**Minecraft version**
Spigot 1.13.2
1.13.2-R0.1-SNAPSHOT

**Additional context**
World Edit version 7.0.0;214af8a
World Guard Version 7.0.0;02b731f

**Plugins (please dont judge me)**

ServerRestart, KitPvP, Core, ChatReaction, ajParkour, OreSheep, Realistic_World, LuckPerms, WorldEdit, Spawntp, HealthBar, betterSleeping, WorldBorder, TangledMaze, ProtocolLib, InventoryRollback, AdvancedPortals, tpa, PocketGames, VoidGenerator, ArvinLib, mcMMO, Vault, GWarp, DeathTax, Herochat, LotteryPool, PerWorldInventory, HolographicDisplays, PlotSquared, WorldGuard, WorldGuardExtraFlags, Companions, TNTRun_reloaded, Jobs, ExtraContexts, Multiverse-Core, Citizens, CrazyAuctions, TAB, GriefPrevention, MiniaturePets, ChestShop, GCore, MV-ChatAlias, TheNewEconomy, Holograms, GParticles, Quests, BossShopPro, RandomTeleport, CommandNPC, Multiverse-NetherPortals, Bank, AreaShop, PlayerShops, BettingGames, CrateReloaded, CommandSigns, CrateReloadedNPC, CitizensIntergration

**Comment by GorgeousOne** [comment]
Hey  @nunavailabul,
that's an interesting bug, I never experienced it.
I think I made a little sloppy mistake when checking permissions. 

Maybe the bug does not appear if you use:
/tangledmaze wand
and before clicking anywhere:
/tangledmaze select rect

I hope this does the magic for now ._.
I will try to fix the bug soon.

Have a nice day
GorgeousOne

**Comment by nunavailabul** [comment]
Thank you!!!  I LOVE this plugin.  TY so much for your help :D

**Comment by GorgeousOne** [comment]
I'm glad the I could help!
