### ISSUE TITLE
1.16.5 not supported ?

### ISSUE THREAD

**Issue by FakEEE14** [GorgeousOne/TangledMazes#30]
**Describe the bug**
increasing path width and length make the plugin go brrrrrr

**To Reproduce**
on a command /tm build 

**Minecraft version**1.16.5 paper latest build

**Additional context**
[18:29:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'maze' in plugin TangledMaze v1.4.2        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-439]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-439]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-439]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.IllegalArgumentException: This exit does not seem to touch the maze.
        at me.gorgeousone.tangledmaze.generation.pathmap.ExitSegmentFactory.getExitFacing(ExitSegmentFactory.java:35) ~[?:?]
        at me.gorgeousone.tangledmaze.generation.pathmap.ExitSegmentFactory.createExitSegment(ExitSegmentFactory.java:62) ~[?:?]
        at me.gorgeousone.tangledmaze.generation.terrainmap.TerrainMapFactory.populateMap(TerrainMapFactory.java:61) ~[?:?]
        at me.gorgeousone.tangledmaze.generation.terrainmap.TerrainMapFactory.createTerrainMapOf(TerrainMapFactory.java:32) ~[?:?]
        at me.gorgeousone.tangledmaze.handlers.BuildHandler.buildMazePart(BuildHandler.java:87) ~[?:?]
        at me.gorgeousone.tangledmaze.commands.BuildMaze.onCommand(BuildMaze.java:104) ~[?:?]
        at me.gorgeousone.cmdframework.command.ArgCommand.onCommand(ArgCommand.java:58) ~[?:?]
        at me.gorgeousone.cmdframework.command.BasicCommand.execute(BasicCommand.java:82) ~[?:?]
        at me.gorgeousone.cmdframework.command.ParentCommand.onCommand(ParentCommand.java:44) ~[?:?]
        at me.gorgeousone.cmdframework.command.BasicCommand.execute(BasicCommand.java:82) ~[?:?]
        at me.gorgeousone.cmdframework.handlers.CommandHandler.onCommand(CommandHandler.java:42) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-439]        ... 19 more

**Comment by GorgeousOne** [comment]
Did this bug occure on several occasions, or was it one specific maze? Could you link a picture of a maze (before everything is going brrr)?
And by how much did you increase the path width/length?
With these information it would be easier for me to reproduce the bug.

**Comment by FakEEE14** [comment]
it's a simple circle maze i know what cuase the problem
when you make the width of the path bigger you need to make sure your exit are not to  close to each other
if you set the path width on 3 and your exit are to close to each other this happen
example if you make the width by 3 and you set the exit like this
![Untitled](https://user-images.githubusercontent.com/68513641/108731948-576d3c00-7542-11eb-8b86-4afc3a9cd08a.png)
