### ISSUE TITLE
Configuration option to disable update-checks

### ISSUE THREAD

**Issue by SlimeDog** [GorgeousOne/TangledMazes#31]
**Is your feature request related to a problem? Please describe.**
We employ a custom automagical update-checker, and we block outgoing network connections by plugins. Consequently, TangledMaze's attempt to contact `pastebin.com` fails.

**Describe the solution you'd like**
Please implement a configuration option to disable update checks. 

**Describe alternatives you've considered**
We can ignore the INFO messages, but it would be cleaner to have the option to stop them.

**Comment by GorgeousOne** [comment]
Just out of curiosity, are you getting an internal error? (If so please include stack trace) Or is there just a message in the console:
`Could not check for updates :(`

**Comment by SlimeDog** [comment]
TangledMaze reports only `Unable to check for updates...` -- very clean.

[NetworkInterceptor](https://www.spigotmc.org/resources/networkinterceptor.53351/) produces a stack trace for reference, but that is not an issue for TangledMaze:
```
Sat Nov 06 21:29:52 PDT 2021: Intercepted connection to pastebin.com by plugin TangledMaze
        at me.gorgeousone.tangledmaze.updatecheck.UpdateCheck.getLatestUpdateInfo(UpdateCheck.java:48) [TangledMaze]
        at me.gorgeousone.tangledmaze.updatecheck.UpdateCheck.lambda$run$0(UpdateCheck.java:33) [TangledMaze]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Sat Nov 06 21:29:52 PDT 2021: Blocked connection to pastebin.com by plugin TangledMaze
```
Out of curiosity, why does TangledMaze check for updates at `pastebin.com` rather than using the SpigotMC API (or the Spiget API)?

**Comment by GorgeousOne** [comment]
Oh I just created a paste where I can write down updates and add a description to it.
And I had the feeling that it always took at least 1 day for the SpigotMc API to update the current plugin version. So that annoyed me a bit.
Maybe that's not the most professional way to do it but it worked kind of well for me

**Comment by SlimeDog** [comment]
I believe the SpigotMC update queue has been on a 4-hour cycle for some time now. But YMMV.

**Comment by SlimeDog** [comment]
I guess there is nothing more to do.
